version: '3'

tasks:
  install-tools:
    desc: Install various tools using Homebrew
    cmds:
      - |
        # List of tools to be installed
        for tool in ansible apr argocd augeas autoconf automake aws-iam-authenticator aws-nuke awscli azure-cli brotli btop c-ares ca-certificates certbot cilium-cli eksctl gcc gnutls go go-task grep groovy helm helmify htop hugo iftop jq jsonnet k9s kind kubecm kubectx kubernetes-cli lazydocker linode-cli lynx m4 md5sha1sum minikube mongocli mtr mysql mysql-client ncurses nmap node npth openjdk openldap openssl@3 openvpn pgloader pipenv pyenv python@3.11 pyyaml readline s3cmd speedtest-cli sqlite telnet tfenv tmux tree trivy velero virtualenv watch wget yq zlib zsh zsh-completions zsh-syntax-highlighting; do
          # Check if the tool is already installed
          if brew list --formula | grep -q "^${tool}\$"; then
            echo "Skipping ${tool}, already installed."
          else
            # Install the tool
            brew install "${tool}"
          fi
        done
      - |
        # Additional tools to be installed as casks
        for cask in chef-workstation devtoys google-cloud-sdk maccy ; do
          if brew list --cask -1 | grep -q "^${cask}\$"; then
            echo "Skipping ${cask}, already installed."
          else
            brew install --cask "${cask}"
          fi
        done
    silent: true

  install-apps:
    desc: Install various applications using Homebrew Cask
    cmds:
      - |
        # List of applications to be installed
        for app in google-chrome brave-browser slack iterm2 notion sublime-text evernote zoom todoist docker visual-studio-code tableplus alfred whatsapp rectangle tunnelblick bitwarden dropbox fing folx hiddenbar lens multipass teamviewer warp; do
          # Check if the application is already installed
          if brew list --cask | grep -q "^${app}\$"; then
            echo "Skipping ${app}, already installed."
          else
            # Install the application
            brew install --cask "${app}"
          fi
        done
    silent: true
  
