version: '3'

tasks:
  install-tools:
    desc: Install various tools using Homebrew
    cmds:
      - |
        # List of tools to be installed
        for tool in ansible apr argocd augeas autoconf automake aws-iam-authenticator aws-nuke awscli azure-cli brotli btop c-ares ca-certificates cairo certbot cffi cilium-cli dialog docutils eksctl fontconfig freetds freetype gcc gdbm gettext gh giflib glib gmp gnupg gnutls go go-task gpatch gpp graphite2 grep groovy harfbuzz helm helmify htop hugo icu4c iftop imlib2 isl jansson jpeg-turbo jq jsonnet jsonnet-bundler jython k8sgpt k9s kind krb5 kubecm kubectx kubernetes-cli lazydocker ldapvi libassuan libcaca libcbor libevent libfido2 libgcrypt libgpg-error libidn2 libksba liblinear libmpc libnghttp2 libpng libpq libssh2 libtasn1 libtiff libtool libunistring libusb libuv libx11 libxau libxcb libxdmcp libxext libxrender libyaml linode-cli little-cms2 llvm@12 lua lua@5.3 lynx lz4 lzo m4 md5sha1sum minikube mongocli mongodb-community@4.2 mpdecimal mpfr mtr mysql mysql-client ncurses nettle nmap node npth oniguruma openjdk openldap openssl@1.1 openssl@3 openvpn p11-kit pcre pcre2 pgloader pinentry pipenv pixman pkcs11-helper pkg-config popt protobuf@21 pycparser pyenv pygments python-certifi python-cryptography python-dateutil python-distlib python-filelock python-jinja python-lxml python-markupsafe python-packaging python-platformdirs python-pyparsing python-pytz python-setuptools python@3.10 python@3.11 python@3.12 pyyaml readline s3cmd sbcl six speedtest-cli sqlite telnet tfenv tmux tree trivy unbound unixodbc utf8proc velero virtualenv watch wget xerces-c xmlstarlet xorgproto xz yq zlib zsh zsh-completions zsh-syntax-highlighting zstd; do
          # Check if the tool is already installed
          if brew list --formula | grep -q "^${tool}\$"; then
            echo "Skipping ${tool}, already installed."
          else
            # Install the tool
            brew install "${tool}"
          fi
        done
      - |
        # Additional tools to be installed as casks
        for cask in chef-workstation devtoys google-cloud-sdk maccy ; do
          if brew list --cask -1 | grep -q "^${cask}\$"; then
            echo "Skipping ${cask}, already installed."
          else
            brew install --cask "${cask}"
          fi
        done
    silent: true

  install-apps:
    desc: Install various applications using Homebrew Cask
    cmds:
      - |
        # List of applications to be installed
        for app in google-chrome brave-browser slack iterm2 notion sublime-text evernote zoom todoist docker visual-studio-code tableplus alfred whatsapp rectangle tunnelblick bitwarden dropbox fing folx hiddenbar lens multipass teamviewer warp; do
          # Check if the application is already installed
          if brew list --cask | grep -q "^${app}\$"; then
            echo "Skipping ${app}, already installed."
          else
            # Install the application
            brew install --cask "${app}"
          fi
        done
    silent: true
  
